# Generated by Django 5.1.6 on 2025-02-19 07:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField(null=True)),
                ('author', models.CharField(max_length=100)),
                ('create_data', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
