# Generated by Django 5.1.6 on 2025-02-20 07:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('id_author', models.IntegerField()),
                ('image', models.ImageField(null=True, upload_to='')),
                ('price', models.IntegerField(null=True)),
                ('content', models.TextField(null=True)),
                ('data_pub', models.DateTimeField(default=django.utils.timezone.now)),
                ('enabled', models.BooleanField()),
                ('reiting', models.PositiveSmallIntegerField(null=True)),
            ],
        ),
    ]
