# Generated by Django 5.1.6 on 2025-02-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_author_alter_book_id_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id_author',
            field=models.IntegerField(),
        ),
    ]
