# Generated by Django 5.1.6 on 2025-02-20 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_book_id_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.author'),
        ),
    ]
