# Generated by Django 5.1.6 on 2025-02-27 07:37

import django.db.models.deletion
import mptt.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_rubric'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='id_rubric',
            field=mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.rubric'),
        ),
    ]
