# Generated by Django 5.1.6 on 2025-04-09 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_author_image_alter_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='count_view',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='authors'),
        ),
    ]
