# Generated by Django 5.1.6 on 2025-04-23 07:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_book_count_view_alter_author_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('mini_content', models.TextField(null=True)),
                ('content', models.TextField(null=True)),
                ('cur_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('enabled', models.BooleanField()),
            ],
        ),
    ]
