# Generated by Django 5.1.6 on 2025-05-01 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_new_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isnew',
            field=models.BooleanField(null=True),
        ),
    ]
